### ISSUE TITLE
Architecture related opinions/queries

### ISSUE THREAD

**Issue by manoj-ms** [target/cloudpunch#18]
Would it be possible to merge roles of local machine and Master for sake of simplicity ? I am playing around with this code for sometime, and tying to understand design decisions. 

-MS

PS: Code is being cooked for submission.

**Comment by JacobCalmes** [comment]
@manoj-ms I can't think of anything right away that would prevent those two roles from merging together. The main design choice to keep them separated was to not have the local machine opening up listening ports.

I could investigate this further to find any potential issues. I am currently working on a 2.0 release with a lot of changes to fix inconsistencies and simplify parts of the code. This possibly could be included in the 2.0 release or a later release based on how it turns out.

**Comment by manoj-ms** [comment]
This answered my question.
